[package]
name = "strangify"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.8.0", features = ["v4"] }
clap = { version = "4.5.4", features = ["derive"] }
image = "0.25.1"
rand = "0.8.5"
rustface = "0.1.7"
