apiVersion: apps/v1
kind: Deployment
metadata:
  name: strangify-app-deployment
  labels:
    app: strangify-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strangify-app
  template:
    metadata:
      labels:
        app: strangify-app
    spec:
      containers:
      - name: strangify-app-deployment
        image: strangify
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080