apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: strangify-app-deployment
spec:
 selector:
   # Selector for Pods
   app: strangify-app
 ports:
   # Port Map
 - port: 8080
   targetPort: 8080
   protocol: TCP
 type: LoadBalancer